const functions=require('firebase-functions');const admin=require('firebase-admin');const express=require('express');const cors=require('cors');const crypto=require('crypto');admin.initializeApp();const db=admin.database();const app=express();app.use(cors({origin:true}));app.use(express.json());
const PLANS={mensal:{name:'Plano Mensal',value:19.90,days:30},trimestral:{name:'Plano Trimestral',value:49.90,days:90},anual:{name:'Plano Anual',value:149.90,days:365},vitalicio:{name:'Acesso Vitalício',value:299.90,days:36500}};
async function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Não autenticado.'});req.user=await admin.auth().verifyIdToken(h.slice(7));next()}catch(e){res.status(401).json({error:'Sessão inválida.'})}}
const mpToken=()=>process.env.MERCADO_PAGO_ACCESS_TOKEN||functions.config().mercadopago?.token;
async function mp(path,options={}){const token=mpToken();if(!token)throw new Error('MERCADO_PAGO_ACCESS_TOKEN não configurado no servidor.');const r=await fetch('https://api.mercadopago.com'+path,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});const out=await r.json();if(!r.ok)throw new Error(out.message||'Erro Mercado Pago');return out}
app.post('/createPix',auth,async(req,res)=>{try{const plan=PLANS[req.body.planId];if(!plan)return res.status(400).json({error:'Plano inválido.'});const profile=(await db.ref('users/'+req.user.uid).once('value')).val();if(!profile)return res.status(404).json({error:'Cadastro não encontrado.'});const idempotency=crypto.randomUUID();const expires=new Date(Date.now()+30*60000).toISOString();const body={transaction_amount:plan.value,description:'Personal Trainer Avançado Pro - '+plan.name,payment_method_id:'pix',date_of_expiration:expires,external_reference:req.user.uid+'|'+req.body.planId,payer:{email:profile.email||req.user.email,first_name:String(profile.name||'Cliente').split(' ')[0],last_name:String(profile.name||'').split(' ').slice(1).join(' ')||'Cliente',identification:{type:'CPF',number:String(profile.cpf||'').replace(/\D/g,'')}}};const pay=await mp('/v1/payments',{method:'POST',headers:{'X-Idempotency-Key':idempotency},body:JSON.stringify(body)});const data={userId:req.user.uid,userName:profile.name||'',userEmail:profile.email||req.user.email||'',planId:req.body.planId,planName:plan.name,amount:plan.value,status:pay.status||'pending',mercadoPagoId:String(pay.id),qrCode:pay.point_of_interaction?.transaction_data?.qr_code||'',qrCodeBase64:pay.point_of_interaction?.transaction_data?.qr_code_base64||'',ticketUrl:pay.point_of_interaction?.transaction_data?.ticket_url||'',createdAt:new Date().toISOString(),expiresAt:expires};await db.ref('payments/'+pay.id).set(data);res.json({payment:{id:String(pay.id),...data}})}catch(e){console.error(e);res.status(500).json({error:e.message})}});
app.get('/paymentStatus',auth,async(req,res)=>{try{const id=String(req.query.id||'');const snap=await db.ref('payments/'+id).once('value'),local=snap.val();if(!local||local.userId!==req.user.uid)return res.status(404).json({error:'Pagamento não encontrado.'});const pay=await mp('/v1/payments/'+encodeURIComponent(id));await syncPayment(pay,local);res.json({payment:{id,...local,status:pay.status}})}catch(e){res.status(500).json({error:e.message})}});
app.get('/latestPayment',auth,async(req,res)=>{const snap=await db.ref('payments').orderByChild('userId').equalTo(req.user.uid).limitToLast(1).once('value');const rows=snap.val()||{},id=Object.keys(rows)[0];res.json({payment:id?{id,...rows[id]}:null})});
async function syncPayment(pay,local){const id=String(pay.id),updates={status:pay.status,statusDetail:pay.status_detail||'',updatedAt:new Date().toISOString()};if(pay.status==='approved'&&local.status!=='approved'){const plan=PLANS[local.planId];const userSnap=await db.ref('users/'+local.userId).once('value'),u=userSnap.val()||{};const base=u.expiresAt&&new Date(u.expiresAt)>new Date()?new Date(u.expiresAt):new Date();const exp=new Date(base.getTime()+plan.days*86400000);updates.approvedAt=new Date().toISOString();await db.ref('users/'+local.userId).update({status:'ativo',plan:local.planId,expiresAt:exp.toISOString(),lastPaymentId:id})}await db.ref('payments/'+id).update(updates)}
app.post('/webhook',async(req,res)=>{res.sendStatus(200);try{const id=req.query['data.id']||req.body?.data?.id||req.query.id;if(!id)return;const pay=await mp('/v1/payments/'+encodeURIComponent(id));const local=(await db.ref('payments/'+id).once('value')).val();if(local)await syncPayment(pay,local)}catch(e){console.error('webhook',e)}});
exports.api=functions.https.onRequest(app);
